name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Code
      run: ./build.ps1
      shell: pwsh
    - name: Run Action
      uses: octogeeks/dotnet-action-template@${{ github.sha }} # change this to point to your custom action repo
      id: sample
      with:
        milliseconds: 5000
    - name: Test Outputs
      run: |
        if ("${{ steps.sample.outputs.time }}") {
          Write-Output "Output Value Found [${{ steps.sample.outputs.time }}]"
        } else {
          Write-Error "No output value found"
          exit 1
        }
      shell: pwsh
